apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-hooks
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  hook-healthz.json: |
    [{
      "id": "healthz",
      "execute-command": "/scripts/raw/healthz",
      "response-message": "OK"
    }]
{{- if .Values.hooksConfig }}
  hooks-config.json: |
    {{ .Values.hooksConfig | nindent 4 }}
{{- end }}
